### ISSUE TITLE
Uphill Downhill are not accurate

### ISSUE THREAD

**Issue by byrod** [tkrajina/gpxpy#252] opened 2022-10-31 08:53 UTC
Hello I have an issue with the get_uphill_downhill()

Downhill and uphill are ok if upload my gpx on this website for example (visugpx.c*m)
Uphill / Downhill : ~ +228m  -230 m

With gpxinfo they are:
Total uphill: 480.07m
Total downhill: 259.27m

[SportsTracker-Walking-20210614-60c7399c5dce230db45a63a4.zip](https://github.com/tkrajina/gpxpy/files/9899532/SportsTracker-Walking-20210614-60c7399c5dce230db45a63a4.zip)

I didn't find any help by searching by myself, so I post here. 
Sorry if this is not an issue.

**Comment by tkrajina** [comment] 2022-11-01 06:55
The problem is that the first few points in your track have no elevations and gpxpy is treating that as elevation=0.

I changed that now (https://github.com/tkrajina/gpxpy/commit/4ca77c1dc6e5bbf39d045d288e39af5873ba086f) and it should be fixed in the new version.

**Closed by tkrajina** 2022-11-01 06:55 UTC

**Comment by byrod** [comment] 2022-11-01 09:16
Thank you !
