### ISSUE TITLE
Can no longer feed a file to gpxpy.parse() in Python 3 / Django 2.2

### ISSUE THREAD

**Issue by ramonakira** [tkrajina/gpxpy#175] opened 2019-06-14 08:33 UTC
Hi,

In a site we built using Django 1.11 and Python 2.7 the following would work:

        try:
            gpx_data = gpxpy.parse(gpx_file)
        except GPXException:
            raise ValidationError(_('Invalid GPX file.'))

(where gpx_file is from a django FileField)

After upgrading to Python 3 and Django 2 the above does not work anymore, resulting in a `gpxpy.gpx.GPXXMLSyntaxException: Error parsing XML: Start tag expected, '<' not found, line 1, column 1`

A workaround is:

        try:
            gpx_string = str(gpx_file.read().decode())
            gpx_data = gpxpy.parse(gpx_string)
        except GPXException:
            raise ValidationError(_('Invalid GPX file.'))

**Comment by tkrajina** [comment] 2019-06-14 08:38
That's an error from an underlying XML parses. Can you provide the GPX file, and is it possible that(as the error says) `<` isn't found on line 1 column 1?

**Comment by tkrajina** [comment] 2019-12-18 16:41
@ramonakira can you send me a sample gpx file when this happens? I need it for a test.

**Comment by tkrajina** [comment] 2019-12-18 17:29
I thought a bit more about this, and I think I'll close this issue for now. Because, from inside `gpxpy` it's totally not clear why (and when) should I call `.decode()` if it's available after `.read()`. I understand it fixes a problem for `FileField`s from Django. But it works for normal file IO objects. 

I agree with you that it's an issue, but I'm not 100% sure it should be fixed inside gpxpy. The argument in `parse()` must be a string or a file (the arg is named `xml_or_file`). If there is a way to reproduce it with GPX files and normal file-like objects, I'll add this fix.

**Closed by tkrajina** 2019-12-18 17:29 UTC
Labels: feature-request

**Comment by hyperknot** [comment] 2020-06-17 00:16
This bug bit me on Pyramid's file upload. The fix is very simple though, run `decode()` if the type is `bytes`, but not when it is `string`. 

I don't know how to make it compatible with 2.7, but in py3 this would be a straightforward fix.

**Comment by tkrajina** [comment] 2020-06-17 05:28
@hyperknot fixed now in 1672f15d3871694eb324b0e3d39d4d69b1791dcf (still in `dev` but I'll merge/release it after more testing)

**Comment by hyperknot** [comment] 2020-06-17 07:16
Looks good!
